# -*- coding: utf-8 -*-
# @author: Douglas

<ControllerBDAtualizar>:

    FloatLayout:
        id: bd_atualizar
        bd_atualizar_popup_confirmacao: bd_atualizar_popup_confirmacao.__self__
        bd_atualizar_popup_importarFasta: bd_atualizar_popup_importarFasta.__self__
        Label:
            text: 'Nome:'
            pos: (root.width / 5) * 1, (root.height / 8) * 6
            size_hint: .1, .05

        Spinner:
            id: bd_atualizar_nome
            text: 'Sem resultados'
            values: 'Sem resultados'
            pos: (root.width / 5) * 2, (root.height / 8) * 6
            size_hint: .4, .05
            self: root.obterDescricoes()

        Label:
            text: 'Tipo:'
            pos: (root.width / 5) * 1, (root.height / 8) * 5
            size_hint: .1, .1

        CheckBox:
            group: 'bd_atualizar_tipo'
            id: bd_atualizar_tipo_dna
            active: True
            pos: (root.width / 20) * 7.2, (root.height / 8) * 5
            size_hint: .1, .1
        Label:
            text: 'DNA'
            pos: (root.width / 20) * 8.2 , (root.height / 8) * 5
            size_hint: .1, .1
            
        CheckBox:
            group: 'bd_atualizar_tipo'
            id: bd_atualizar_tipo_proteina
            pos: (root.width / 20) * 11.2, (root.height / 8) * 5
            size_hint: .1, .1
        Label:
            text: 'Prote\u00EDna'
            pos: (root.width / 20) * 12.3, (root.height / 8) * 5
            size_hint: .1, .1

        Label:
            text: 'Sequ\u00EAncia:'
            pos: (root.width / 5) * 1, (root.height / 8) * 4
            size_hint: .1, .1

        TextInput:
            id: bd_atualizar_seq
            pos: (root.width / 5) * 2, (root.height / 8) * 3
            size_hint: .4, .2

        Button:
            text: "Importar dados de um arquivo .fasta"
            size_hint: .8, .07
            pos: (root.width / 10) * 1, (root.height / 20) * 5
            on_release: bd_atualizar_popup_importarFasta.open()

        Button:
            text: "Atualizar"
            size_hint: .8, .07
            pos: (root.width / 10) * 1, (root.height / 20) * 3
            on_release: root.atualizar(bd_atualizar_nome.text, bd_atualizar_tipo_dna.active, bd_atualizar_seq.text), bd_atualizar_popup_confirmacao.open()

        Popup:
            id: bd_atualizar_popup_confirmacao
            on_parent: if self.parent == bd_atualizar: bd_atualizar.remove_widget(self)
            title: 'Resultado'
            size_hint: .4, .4
            content: bd_atualizar_popup
            FloatLayout:
                id: bd_atualizar_popup
                Label:
                    id: bd_atualizar_popup_label
                    text: 'Dado atualizado com sucesso!'
                    pos: (root.width / 20) * 9, (root.height / 20) * 11
                    size_hint: .1, .1
                Button:
                    text: 'OK'
                    size_hint: .8, .2
                    pos: (root.width / 20) * 7, (root.height / 20) * 7
                    on_release: bd_atualizar_popup_confirmacao.dismiss()

        Popup:
            id: bd_atualizar_popup_importarFasta
            on_parent: if self.parent == bd_atualizar: bd_atualizar.remove_widget(self)
            title: 'Resultado'
            size_hint: 1, 1
            content: bd_atualizar_importarFasta
            FloatLayout:
                id: bd_atualizar_importarFasta
                FileChooserIconView:
                    id: filechooser
                    path: root.obterCaminho()
                    on_selection: root.preencherDados(filechooser.path, filechooser.selection), bd_atualizar_popup_importarFasta.dismiss()