# -*- coding: utf-8 -*-
# @author: Douglas

<ControllerBDDeletar>:

    FloatLayout:
        Label:
            text: 'Nome da sequ\u00EAncia:'
            pos: (root.width / 5) * 1, (root.height / 8) * 6
            size_hint: .1, .05
            
        Spinner:
            id: bd_deletar_nome
            text: 'Sem resultados'
            values: 'Sem resultados'
            pos: (root.width / 5) * 2, (root.height / 8) * 6
            size_hint: .4, .05
            self: root.obterDescricoes()

        Button:
            text: "Deletar"
            size_hint: .8, .07
            pos: (root.width / 10) * 1, (root.height / 20) * 3
            on_release: root.deletar(bd_deletar_nome.text), root.obterDescricoes()