# -*- coding: utf-8 -*-
# @author: Douglas

<ControllerBioInf>:

    FloatLayout:
        Button:
            text: "Converter DNA\n para prote\u00EDna"
            pos: (root.width / 3) * 0, (root.height / 8) * 7
            halign: 'center'
            size_hint: .333, .1
            on_release: root.bioinf_converter()
        Button:
            text: "Complemento reverso\n de um DNA"
            pos: (root.width / 3) * 1, (root.height / 8) * 7
            halign: 'center'
            size_hint: .333, .1
            on_release: root.bioinf_complemento()
        Button:
            text: "Calcular massa molecular\n de uma prote\u00EDna"
            pos: (root.width / 3) * 2, (root.height / 8) * 7
            halign: 'center'
            size_hint: .333, .1
            on_release: root.bioinf_massa()